<main class="container py-5">  
    <article class="card col-12 p-5">  
        <header>  
            <h2 class="card-title mb-3">  
                <?= $data['product']->getName() ?> 
            </h2>  
            <h3 class="card-subtitle mb-4">  
            <?php 
            $categories = $data['product']->getCategories();
            foreach($categories as $category){ echo $category['name']." ";} ?>  
            </h3>  
        </header>  
        <p class="card-text">  
            <?= $data['product']->getDescription() ?>  
        </p>  
        <footer>  
            <p class="btn btn-light">  
                <?= $data['product']->getPrice() ?>  
            </p>  
        </footer>  
    </article>  
</main>